---
title: "Project Presentation"
subtitle: "The data we have chosen"
format: 
  revealjs
highlight-style: a11y
execute:
  code-link: true
  echo: true
editor_options: 
  chunk_output_type: console
---

## Outline

* Your presentation should generally follow the same structure as your write-up. 

* Each team will have 5 minutes for their presentation, and each team member must speak (roughly equally) during this time. 

* Your presentation will be created using `Quarto`, which allows you to write slides using the same coding structure you’re used to with `Rmarkdown`. 

* This is a sample Quarto slide template you can edit to your desire to create your presentation. 

## Rubric

* Roughly I recommend 1 slide for introduction, 2 slides for Question 1, ans 2 slides for Question 2. 
  + You can imagine spending roughly one minute on each slide.
  + You should feel free to have more (or fewer) slides. 
  
* Your evaluation will be based on your content, professionalism (including sticking to time), and your performance during the Q&A (question and answer). We don’t care how many slides you use to do this.